"use client";

import { ChevronDown, Search, SlidersHorizontal } from "lucide-react";

import type { WidgetRendererProps } from "@/types/admin";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/utils/cn";

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <label className="mb-2 block text-[15px] font-medium leading-[22px] text-foreground">
      {children}
    </label>
  );
}

function InputShell({
  children,
  className
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "flex min-h-11 items-center gap-2 rounded-lg border border-border/70 bg-white px-3 text-[13px] font-normal leading-[20px] text-foreground",
        className
      )}
    >
      {children}
    </div>
  );
}

export function ControlsShowcaseWidget({ config }: WidgetRendererProps) {
  return (
    <Card>
      <CardHeader className="pb-4">
        <div className="flex items-start justify-between gap-4">
          <div>
            <CardTitle>{config.title}</CardTitle>
            <p className="mt-1 text-[13px] font-normal leading-[20px] text-muted-foreground">
              Theme-aligned controls for buttons, forms, filters, and state inputs.
            </p>
          </div>
          <Badge>UI Kit</Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <section className="space-y-3">
          <h3 className="text-[18px] font-medium leading-[28px]">Buttons</h3>
          <div className="flex flex-wrap gap-3">
            <Button>Primary</Button>
            <Button variant="soft">Secondary</Button>
            <Button variant="outline">Outline</Button>
            <Button variant="ghost">Ghost</Button>
            <Button size="sm">Small Action</Button>
          </div>
        </section>

        <section className="grid gap-5 lg:grid-cols-2">
          <div>
            <FieldLabel>Search Input</FieldLabel>
            <InputShell>
              <Search className="h-4 w-4 text-muted-foreground" />
              <input
                defaultValue="Find components"
                className="w-full bg-transparent outline-none"
              />
            </InputShell>
          </div>
          <div>
            <FieldLabel>Dropdown</FieldLabel>
            <InputShell className="justify-between">
              <span>Status: Active</span>
              <ChevronDown className="h-4 w-4 text-muted-foreground" />
            </InputShell>
          </div>
          <div>
            <FieldLabel>Text Input</FieldLabel>
            <InputShell>
              <input
                defaultValue="Acme workspace"
                className="w-full bg-transparent outline-none"
              />
            </InputShell>
          </div>
          <div>
            <FieldLabel>Filter Control</FieldLabel>
            <InputShell className="justify-between">
              <span className="inline-flex items-center gap-2">
                <SlidersHorizontal className="h-4 w-4 text-muted-foreground" />
                Advanced filters
              </span>
              <Badge>3</Badge>
            </InputShell>
          </div>
        </section>

        <section>
          <FieldLabel>Textarea</FieldLabel>
          <textarea
            defaultValue="This panel is generated by a page config and rendered by the registry-driven widget system."
            className="min-h-28 w-full rounded-lg border border-border/70 bg-white px-3 py-3 text-[13px] font-normal leading-[20px] text-foreground outline-none"
          />
        </section>

        <section className="grid gap-5 lg:grid-cols-3">
          <div className="space-y-3 rounded-lg border border-border/70 bg-muted/30 p-4">
            <h3 className="text-[18px] font-medium leading-[28px]">Checkboxes</h3>
            <label className="flex cursor-pointer items-center gap-3 text-[13px] leading-[20px]">
              <input type="checkbox" defaultChecked className="h-4 w-4 accent-[hsl(var(--primary))]" />
              Email notifications
            </label>
            <label className="flex cursor-pointer items-center gap-3 text-[13px] leading-[20px]">
              <input type="checkbox" className="h-4 w-4 accent-[hsl(var(--primary))]" />
              Weekly summary
            </label>
          </div>

          <div className="space-y-3 rounded-lg border border-border/70 bg-muted/30 p-4">
            <h3 className="text-[18px] font-medium leading-[28px]">Radio Group</h3>
            <label className="flex cursor-pointer items-center gap-3 text-[13px] leading-[20px]">
              <input type="radio" name="density" defaultChecked className="h-4 w-4 accent-[hsl(var(--primary))]" />
              Comfortable
            </label>
            <label className="flex cursor-pointer items-center gap-3 text-[13px] leading-[20px]">
              <input type="radio" name="density" className="h-4 w-4 accent-[hsl(var(--primary))]" />
              Compact
            </label>
          </div>

          <div className="space-y-3 rounded-lg border border-border/70 bg-muted/30 p-4">
            <h3 className="text-[18px] font-medium leading-[28px]">Toggle States</h3>
            <div className="flex items-center justify-between rounded-lg bg-white px-3 py-2">
              <span className="text-[13px] leading-[20px]">Auto save</span>
              <button
                type="button"
                className="relative h-6 w-11 rounded-full bg-primary"
                aria-label="Auto save enabled"
              >
                <span className="absolute right-1 top-1 h-4 w-4 rounded-full bg-white" />
              </button>
            </div>
            <div className="flex items-center justify-between rounded-lg bg-white px-3 py-2">
              <span className="text-[13px] leading-[20px]">Audit trail</span>
              <button
                type="button"
                className="relative h-6 w-11 rounded-full bg-muted"
                aria-label="Audit trail disabled"
              >
                <span className="absolute left-1 top-1 h-4 w-4 rounded-full bg-white" />
              </button>
            </div>
          </div>
        </section>
      </CardContent>
    </Card>
  );
}
